// IWYU pragma: private, include "kmock/kmock.h"
// IWYU pragma: friend kmock/.*

#ifndef KHULNASOFTMOCK_INCLUDE_KMOCK_INTERNAL_CUSTOM_KMOCK_GENERATED_ACTIONS_H_
#define KHULNASOFTMOCK_INCLUDE_KMOCK_INTERNAL_CUSTOM_KMOCK_GENERATED_ACTIONS_H_

#endif  // KHULNASOFTMOCK_INCLUDE_KMOCK_INTERNAL_CUSTOM_KMOCK_GENERATED_ACTIONS_H_
